export const EVENT_LOAD_REQUEST = 'EVENT_LOAD_REQUEST';
export const EVENT_LOAD_SUCCESS = 'EVENT_LOAD_SUCCESS';
export const EVENT_LOAD_FAIL = 'EVENT_LOAD_FAIL';

export const EVENT_CREATE_REQUEST = 'EVENT_CREATE_REQUEST';
export const EVENT_CREATE_SUCCESS = 'EVENT_CREATE_SUCCESS';
export const EVENT_CREATE_FAIL = 'EVENT_CREATE_FAIL';
export const EVENT_CREATE_CLEAR = 'EVENT_CREATE_CLEAR';

export const EVENT_REQUEST_CREATE = 'EVENT_REQUEST_CREATE';
export const EVENT_REQUEST_SUCCESS = 'EVENT_REQUEST_SUCCESS';
export const EVENT_REQUEST_FAIL = 'EVENT_REQUEST_FAIL';
export const EVENT_REQUEST_CLEAR = 'EVENT_REQUEST_CLEAR';
