export const REQUESTFORM_EVENT_LOAD = 'REQUESTFORM_EVENT_LOAD';
export const REQUESTFORM_EVENT_SUCCESS = 'REQUESTFORM_EVENT_SUCCESS';
export const REQUESTFORM_EVENT_ERROR = 'REQUESTFORM_EVENT_ERROR';
export const REQUESTFORM_EVENT_CLEAR = 'REQUESTFORM_EVENT_CLEAR';
