export const REQUESTFORM_EVENT_LOAD = 'REQUESTFORM_EVENT_LOAD';
export const REQUESTFORM_EVENT_SUCCESS = 'REQUESTFORM_EVENT_SUCCESS';
export const REQUESTFORM_EVENT_ERROR = 'REQUESTFORM_EVENT_ERROR';
export const REQUESTFORM_EVENT_CLEAR = 'REQUESTFORM_EVENT_CLEAR';

export const REQUESTFORM_APPLY_REQUEST = 'REQUESTFORM_APPLY_REQUEST';
export const REQUESTFORM_APPLY_SUCCESS = 'REQUESTFORM_APPLY_SUCCESS';
export const REQUESTFORM_APPLY_ERROR = 'REQUESTFORM_APPLY_ERROR';
export const REQUESTFORM_APPLY_CLEAR = 'REQUESTFORM_APPLY_CLEAR';
