export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST"
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL"

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST"
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS"
export const USER_CREATE_FAIL = "USER_CREATE_FAIL"
export const USER_CREATE_CLEAR = "USER_CREATE_CLEAR"

export const USERS_LIST_LOAD_REQUEST = "USERS_LIST_LOAD_REQUEST"
export const USERS_LIST_LOAD_SUCCESS = "USERS_LIST_LOAD_SUCCESS"
export const USERS_LIST_LOAD_FAIL = "USERS_LIST_LOAD_FAIL"

export const USERS_FILTER_LOAD_REQUEST = "USERS_FILTER_LOAD_REQUEST"
export const USERS_FILTER_LOAD_SUCCESS = "USERS_FILTER_LOAD_SUCCESS"
export const USERS_FILTER_LOAD_FAIL = "USERS_FILTER_LOAD_FAIL"
